
default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5

development:
  <<: *default
  database: round-out_development

test:
  <<: *default
  database: round-out_test

production:
  <<: *default
  database: round-out_production
  username: round-out
  password: <%= ENV['ROUND-OUT_DATABASE_PASSWORD'] %>
